### ISSUE TITLE
img

### ISSUE THREAD

**Issue by vang007** [ThManHimself/what-the-bleep-should-I-watch#7]
![3658597](https://user-images.githubusercontent.com/84373534/125709298-0f3783b0-74f4-4e0d-a3c9-7672fc8a9b98.jpg)

**Comment by watkincw** [comment]
@vang007 Do we need this image here for any reason at this point?

**Comment by vang007** [comment]
Done

**Comment by vang007** [comment]
No. I was doing a trial and error thing.
